site_name: Jamkit for Developer
repo_url: https://bookjam.github.io/jamkit
pages:
- 잼킷이란?: index.md
- 시작하기: start.md
- 튜토리얼: tutorials.md
- 레시피: recipes.md
- 참조문서: references.md
theme_dir: material
google_analytics: ['UA-30027224-9','bookjam.github.io']
